apiVersion: v1
kind: Secret
metadata:
  name: myfinance-secrets
  namespace: myfinance
type: Opaque
stringData:
  DATABASE_URL: "mysql://app:6BDMr3TSjG@10.42.0.1:3306/myfinance"
  JWT_SECRET: "mf-prod-secret-k8x2vNpL9qWm4rTzYbHj"
