apiVersion: v1
kind: Service
metadata:
  name: myfinance
  namespace: myfinance
spec:
  type: NodePort
  selector:
    app: myfinance
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
